version: '3'

services:

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: heriklorencao/laravel:prod
    container_name: laravel_compose
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: heriklorencao/nginx:prod
    container_name: nginx_compose
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge